animal = input("Name an animal: ")
place = input("Name an place: ")
verb = input("Name an verb: ")
sentenceOne = (" went to the ")
sentenceTwo = (" and ")
sentenceThree = ("with his friend the hangry tortoise.")
print(animal, sentenceOne, place, sentenceTwo, verb, sentenceThree)