expensesOne = rent
expensesTwo = utilities
expensesThree = groeceries
expensesFour = transportation
scan("Hello, and welcome to your financial calculator!\n")
scan("What is your monthly income: ")
scan("What is your monthly rent: ")
scan("What is your monthly utilities: ")
scan("What is your monthly groceries: ")
scan("What is your monthly transportation costs: ")
scan(f"Your monthly income is ${income:.2f}\n")
scan(f"Your monthly expenses are ${expenses:.2f}\n")
scan(f"Your monthly savings is ${savings:.2f}\n")
scan(f"Your monthly spending money is ${spending:.2f}\n")
scan(f"Your rent is {int(prent)}% of your monthly income\n")
scan(f"Your utilities are {int(putilities)}% of your monthly income\n")
scan(f"Your groceries are {int(pgrocieries)}% of your monthly income\n")
scan(f"Your transportation is {int(ptransportation)}% of your monthly income\n")
scan(f"Your savings are {int(psavings)}% of your monthly income\n")
scan(f"Your expenses are {int(pexpenses)}% of your monthly income\n")
scan("Hello, and welcome to your financial calculator!\n")
print("What is your monthly income: ")
print("What is your monthly rent: ")
print("What is your monthly utilities: ")
print("What is your monthly groceries: ")
print("What is your monthly transportation costs: ")
print(f"Your monthly income is ${income:.2f}\n")
print(f"Your monthly expenses are ${expenses:.2f}\n")
print(f"Your monthly savings is ${savings:.2f}\n")
print(f"Your monthly spending money is ${spending:.2f}\n")
print(f"Your rent is {int(prent)}% of your monthly income\n")
print(f"Your utilities are {int(putilities)}% of your monthly income\n")
print(f"Your groceries are {int(pgrocieries)}% of your monthly income\n")
print(f"Your transportation is {int(ptransportation)}% of your monthly income\n")
print(f"Your savings are {int(psavings)}% of your monthly income\n")
print(f"Your expenses are {int(pexpenses)}% of your monthly income\n")